### PR TITLE
Changing the method of getting path to make it Robust

### PR DESCRIPTION
**Pull request by xordux**
This change will make the code more Robust. Using 'inspect' to find out filename and path will work seamlessly with execfile(...) function and PyCharm's Alt+Shift+e (to run the highlighted lines) shortcut.
As mentioned here: https://stackoverflow.com/a/6209894/1484916

### CODE REVIEW

**Comment by gedeck** [comment]
Hello, 

Thank you for submitting the PR. This is a use case that I've not encountered myself. 

I've created a separate PR due to the following reason. The content from this repository is created from ipython notebooks in a separate, private repository. This private repository includes code in the notebooks that create the figures and tables for the book. I therefore make changes in the private repository and synchronize the changes to the public repository while removing this less relevant code and having a cleaner public code repository. 

When I tried your modification in an ipython notebook, it didn't work. It seems that ipython runs the code in a subdirectory of the directory the file is in. I therefore moved the determination of the data directory into a separate module. This module is imported and the `__file__` variable of the module is correctly set and can be used to identify the data directory. I also changed the hardcoded number of directories to move up and check for a `data` folder in every parent directory. With this change, the ipython notebooks still work and the execution of the extracted Python code too. 

What I couldn't test was your use case. If you have time, could you please check the PR #4 (https://github.com/gedeck/practical-statistics-for-data-scientists/pull/4, branch `make-data-directory-detection-more-robust`).

Thank you,

Peter

**Comment by xordux** [comment]
Hi, sorry for late reply. I somehow overlooked the Github notification. 

I tried the new code in Pycharm but it didn't work, even "import common.py" statement threw error. Looks like Pycharm is working exactly opposite of ipython notebook .i.e. running the python file in practical-statistics-for-data-scientists-master directory(and perhaps ipython is running it in practical-statistics-for-data-scientists-master/python/code directory). 

I think this can fixed by putting a if-else statement in the code I shared. As I haven't worked with ipython notebooks yet, I will install it in my PC and test both the cases.

Or you can drop these changes and simply mention(if anyone raises issue) to run code in "practical-statistics-for-data-scientists-master/python/code" directory. That will work too with previous code.

**Comment by gedeck** [comment]
Hello, 

When I update this repository, I extract the Python code into the files from the notebook, so I could add additional code at the start of the file. What about the following (untested)? 
```
import os, sys, inspect
try:
  import common
except ImportError:
  filename = inspect.getframeinfo(inspect.currentframe()).filename
  curr_dir = str(os.path.dirname(os.path.abspath(filename)))
  if curr_dir not in sys.path:
    sys.path.append(curr_dir)
  import common
```

**Comment by xordux** [comment]
Hi,

This also did work, I added a print statement like this:
`try:`
`  import common`
`except ImportError:`
`  filename = inspect.getframeinfo(inspect.currentframe()).filename`
`  curr_dir = str(os.path.dirname(os.path.abspath(filename)))`
`  if curr_dir not in sys.path:`
`    print("adding now")`
`    sys.path.append(curr_dir)`

"adding now" didn't got printed and my system path becomes:
['C:\\Program Files\\JetBrains\\PyCharm Community Edition 2019.2.1\\plugins\\python-ce\\helpers\\pydev', 'C:\\Python3\\Lib', 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2019.2.1\\plugins\\python-ce\\helpers\\third_party\\thriftpy', 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2019.2.1\\plugins\\python-ce\\helpers\\pydev', 'C:\\Python3\\python38.zip', 'C:\\Python3\\DLLs', 'C:\\Python3', 'C:\\Users\\rohitraw\\.virtualenvs\\kaggle', 'C:\\Users\\rohitraw\\.virtualenvs\\kaggle\\lib\\site-packages', 'C:\\Users\\rohitraw\\.virtualenvs\\kaggle\\lib\\site-packages\\setuptools-40.8.0-py3.8.egg', 'C:\\PersonalProjects\\MachineLearning\\practical-statistics-for-data-scientists-master\\practical-statistics-for-data-scientists-master', 'C:/PersonalProjects/MachineLearning/practical-statistics-for-data-scientists-master/practical-statistics-for-data-scientists-master']

**Comment by gedeck** [comment]
I now downloaded pycharm and opened the root directory of the project. When I open the code for Chapter 1, the editor highlights common as 'No module named common'. 

image

I can run the whole file though and the import works.

Selecting the lines and executing (Alt+Shift+e) doesn't work though.
```
import inspect
... import os
... filename = inspect.getframeinfo(inspect.currentframe()).filename
... print(filename)
... curr_dir = str(os.path.dirname(os.path.abspath(filename)))
... print(curr_dir)
... 
<input>
/Users/gedeck/git/practical-statistics-for-data-scientists
```
As you can see the filename from the inspect command is <input> in this case. `os.path.abspath` just adds this to the current working directory (project root), `os.path.dirname` removes it and we get the project directory. 

I tried the following:
```
from pathlib import Path
try:
    import common
    DATA = common.dataDirectory()
except ImportError:
    DATA = Path().resolve() / 'data'
```
This works in pycharm when I execute the file or select this block of text and use (Alt+Shift+e).

**Comment by xordux** [comment]
Yes, it does.

**Comment by gedeck** [comment]
Thank you for the feedback. Let me fix the actual source files and update this repo. Then, I'll close the PR.

**Pull request closed without merging**
