### PR TITLE
Update environment.yml to include conda-forge

### LINKED ISSUE #56: Anaconda - ResolvePackageNotFound
I was trying to clone the repo and run the Python files. While updating the _environment.yml_ file after creating the **_sfds_**, I got this below shown error.
Screenshot from 2023-06-29 16-58-41

### PR DESCRIPTION
**Pull request by gregorywaynepower**
add conda-forge channel for Issue #56

Closes #56

### CODE REVIEW

**Comment by gedeck** [comment]
Yes, fix sklearn version to 1.2 until the issue is resolved

**Comment by gedeck** [comment]
Instead of replacing the pip install in github/workflow, add extra jobs for building with conda and/or mamba. As the pip install run already checks different Python versions, we could restrict conda/mamba to the latest Python version.

**Comment by gregorywaynepower** [comment]
Okay, I’ll roll that up in a later pull request.

**Comment by glemaitre** [comment]
Fixed in https://github.com/scikit-learn-contrib/imbalanced-learn/pull/999.
I'm going to make a release ASAP.

**Comment by gedeck** [comment]
@glemaitre Thank you very much to being responsive.

**Review by gregorywaynepower — COMMENTED** [review]
added fault channel as well

**Review by gedeck — APPROVED** [review]
I'm going to approve this, so that you can merge it when it is ready

**Comment by gregorywaynepower** [comment]
@gedeck I don’t have write access to the repo, so I don’t believe I can merge it.

**Comment by gedeck** [comment]
I merged it now

**Pull request merged**
